// <auto-generated />
namespace Lte.MySqlFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_CdmaKpi_MySql : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_CdmaKpi_MySql));
        
        string IMigrationMetadata.Id
        {
            get { return "201607180641597_Change_CdmaKpi_MySql"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
