// <auto-generated />
namespace Lte.MySqlFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Move_College_Test_Entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Move_College_Test_Entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201608050836340_Move_College_Test_Entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
