// <auto-generated />
namespace Lte.MySqlFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Precise_WorkItem_Cell_Mysql_20160606 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Precise_WorkItem_Cell_Mysql_20160606));
        
        string IMigrationMetadata.Id
        {
            get { return "201606060751035_Precise_WorkItem_Cell_Mysql_20160606"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
