// <auto-generated />
namespace Lte.MySqlFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PlanningSite_AddFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlanningSite_AddFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201703040759297_PlanningSite_AddFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
