// <auto-generated />
namespace Lte.MySqlFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Extend_Csv_File_Info : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Extend_Csv_File_Info));
        
        string IMigrationMetadata.Id
        {
            get { return "201707220138165_Extend_Csv_File_Info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
