// <auto-generated />
namespace Lte.MySqlFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class flow_huawei_add_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(flow_huawei_add_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201702181344248_flow_huawei_add_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
