// <auto-generated />
namespace Lte.MySqlFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_MrGrid_Cluster_Kpi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_MrGrid_Cluster_Kpi));
        
        string IMigrationMetadata.Id
        {
            get { return "201706290842226_Add_MrGrid_Cluster_Kpi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
