// <auto-generated />
namespace Lte.MySqlFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_StationDictionary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_StationDictionary));
        
        string IMigrationMetadata.Id
        {
            get { return "201704250816308_Create_StationDictionary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
