// <auto-generated />
namespace Lte.Parameters.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_LocalSectorId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_LocalSectorId));
        
        string IMigrationMetadata.Id
        {
            get { return "201608011333021_Add_LocalSectorId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
