// <auto-generated />
namespace Lte.Parameters.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Extend_Town_Type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Extend_Town_Type));
        
        string IMigrationMetadata.Id
        {
            get { return "201703150902044_Extend_Town_Type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
